### ISSUE TITLE
feathers-hooks-validate-joi Validator

### ISSUE THREAD

**Issue by saraawss** [feathers-plus/feathers-hooks-validate-joi#11] opened 2018-07-25 00:01 UTC
I have a feathersjs API with a messages service. I want to validate the message model with feathers-hooks-validate-joi module.

Here is my user-hooks.js file:

const validate = require('feathers-hooks-validate-joi');
const {schema} = require('./user.validator');

module.exports = {
  before: {
    create: [validate.form(schema)],
    //others method fields
  }
};
Here is my user.validator.js file:

const Joi = require('joi');

const schema = Joi.object().keys({
  email: Joi.string().trim().min(2).required(),
  password: Joi.string().trim().min(2).required()
});

module.exports = schema;
When I try to post a message via curl:

curl 'http://localhost:3030/users/' -H 'Content-Type: application/json' --data-binary '{ "email": "test@gmail.com", "password": "World" }'

I receive this error message:

{
    "name": "GeneralError",
    "message": "Invalid schema content: ",
    "code": 500,
    "className": "general-error",
    "data": {},
    "errors": {}
}
Please can you help me to fix this problem

**Comment by eddyystop** [comment] 2018-07-25 12:31
First, call the service with this within the server. That'll show if the problem is the schema or how you formatted the curl command.

**Comment by marshallswain** [comment] 2020-02-11 19:42
I'm not able to replicate this issue.  I'm going to close it, but feel free to reopen, @saraawss, if you feel like it's still a problem.

**Closed by marshallswain** 2020-02-11 19:42 UTC
